#!/usr/bin/env python

"""Convert a CLRMame Pro .dat file to JSON.
"""

import sys
import json
from parser import parse

def _usage():
    """Print usage and quit."""
    print """
Usage: {} filename

    filename   the name of the .dat file (clrmame format), or '-'.

If filename is '-', input will be read from STDIN.
""".format(sys.argv[0])
    sys.exit(1)

def _tup2dict(tup, parent=None):
    if parent is None:
        parent = {}
    is_pair = len(tup) == 2 and isinstance(tup[0], str)
    if is_pair:
        key, val = tup
        if not isinstance(val, str):
            val = _tup2dict(val)
        parent[key] = val
    else: # new dict
        for val in tup:
            _tup2dict(val, parent)
    return parent

def main(args):
    """main"""
    if len(args) != 1:
        _usage()
    filename = args[0]
    fileobj = sys.stdin if filename == '-' else open(filename, 'r')
    print "["
    first = True
    for entry in parse(fileobj):
        if not first:
            print ",",
        first = False
        print json.dumps(_tup2dict(entry))
    print "]"

if __name__ == '__main__':
    main(sys.argv[1:])
