#!/usr/bin/env python2

"""Convert a CLRMame Pro .dat file to JSON.
"""

import sys
import json
from parser import parse

def _usage():
    """Print usage and quit."""
    print """
Usage: {} filename

    filename   the name of the .dat file (clrmame format), or '-'.

If filename is '-', input will be read from STDIN.
""".format(sys.argv[0])
    sys.exit(1)

def main(args):
    """main"""
    if len(args) != 1:
        _usage()
    filename = args[0]
    fileobj = sys.stdin if filename == '-' else open(filename, 'r')
    print "["
    first = True
    for entry in parse.to_dict(fileobj):
        if not first:
            print ",",
        first = False
        print json.dumps(entry)
    print "]"

if __name__ == '__main__':
    main(sys.argv[1:])
